version: "3"

services:
  redis:
    image: redis:3.2
    volumes:
      - ./.app/redis/data:/data
    ports:
      - 6379:6379
    restart: always
  app:
    build: .
    depends_on:
      - redis
    volumes:
      - ./.kalilabs:/app/.app
    ports:
      - 80:3000
    environment:
      NODE_ENV: production
      DB_HOST: '10.136.159.26'
      DB_USER: kalilabs
      DB_PASSWORD: ekmfyyU
      REDIS_HOST: redis
